routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LocationController;
use \App\Http\Controllers\CountryController;
use \App\Http\Controllers\CityController;
use \App\Http\Controllers\ListingController;
use \App\Http\Controllers\UserController;
use \App\Http\Controllers\ListingPictureController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Auth::routes();
Route::get('/', [LocationController::class,'Categories'])->name('index');
Route::get('/all/listing', [LocationController::class,'Listing'])->name('listing');
Route::get('/all/city/{slug}', [LocationController::class,'city'])->name('cityListing');
Route::group(['prefix' => 'hotel', 'middleware' => ['auth', 'verified']],function () {

    Route::get('/dashboard',[UserController::class,'index'])->name('Howner');
    Route::get('listings/index',[ListingController::class,'index'])->name('listings.index');
    Route::get('listings/create',[ListingController::class,'create'])->name('listings.create');
    Route::post('listings/store',[ListingController::class,'store'])->name('listings.store');
    Route::get('listings/{id}/edit',[ListingController::class,'edit'])->name('listings.edit');
    Route::patch('listings/{id}',[ListingController::class,'update'])->name('listings.update');
    Route::delete('listings/{id}',[ListingController::class,'destroy'])->name('listings.destroy');
    Route::get('listings/{id}',[ListingController::class,'show'])->name('listings.show');
    Route::post('availability/hotels',[ListingController::class,'Availability'])->name('listings.Availability');
    Route::get('available/hotels/',[ListingController::class,'makeavailable'])->name('hotels.makeAvailability');
    Route::post('photos/delete',[ListingPictureController::class,'destroy'])->name('photos.delete');
    Route::get('/hotel1/ajax',[ListingController::class,'ajax'])->name('hotels.ajax');
    //ya get wala ha oper wala ya nichy wala nechay wala

});
Route::group(['prefix' => 'property', 'middleware' => ['auth', 'verified']],function () {

    Route::get('/dashboard',[UserController::class,'index'])->name('Powner');
    Route::get('listings/index',[ListingController::class,'index'])->name('listings.index');
    Route::get('listings/create',[ListingController::class,'create'])->name('listings.create');
    Route::post('listings/store',[ListingController::class,'store'])->name('listings.store');
    Route::get('listings/{id}/edit',[ListingController::class,'edit'])->name('listings.edit');
    Route::patch('listings/{id}',[ListingController::class,'update'])->name('listings.update');
    Route::delete('listings/{id}',[ListingController::class,'destroy'])->name('listings.destroy');
    Route::get('listings/{id}',[ListingController::class,'show'])->name('listings.show');
    Route::post('availability/hotels',[ListingController::class,'Availability'])->name('listings.Availability');
    Route::get('available/hotels/',[ListingController::class,'makeavailable'])->name('listings.makeAvailability');
    Route::post('photos/delete',[ListingPictureController::class,'destroy'])->name('photos.delete');
    Route::get('/hotel1/ajax',[ListingController::class,'ajax'])->name('hotels.ajax');

});
Route::group(['prefix' => 'user', 'middleware' => ['auth', 'verified']],function () {

    Route::get('/dashboard',[UserController::class,'index'])->name('userDashboard');
    Route::get('listings/index',[ListingController::class,'index'])->name('listings.index');
    Route::get('listings/create',[ListingController::class,'create'])->name('listings.create');
    Route::post('listings/store',[ListingController::class,'store'])->name('listings.store');
    Route::get('listings/{id}/edit',[ListingController::class,'edit'])->name('listings.edit');
    Route::patch('listings/{id}',[ListingController::class,'update'])->name('listings.update');
    Route::delete('listings/{id}',[ListingController::class,'destroy'])->name('listings.destroy');
    Route::get('listings/{id}',[ListingController::class,'show'])->name('listings.show');

    Route::post('availability/hotels',[ListingController::class,'Availability'])->name('listings.Availability');
    Route::get('available/hotels/',[ListingController::class,'makeavailable'])->name('listings.makeAvailability');
    Route::post('photos/delete',[ListingPictureController::class,'destroy'])->name('photos.delete');
    Route::get('/hotel1/ajax',[ListingController::class,'ajax'])->name('hotels.ajax');
});
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'verified']],function () {

    Route::get('/dashboard',[UserController::class,'index'])->name('adminDashboard');
    Route::get('listings/index',[ListingController::class,'index'])->name('listings.index');
    Route::get('listings/create',[ListingController::class,'create'])->name('listings.create');
    Route::post('listings/store',[ListingController::class,'store'])->name('listings.store');
    Route::get('listings/{id}/edit',[ListingController::class,'edit'])->name('listings.edit');
    Route::patch('listings/{id}',[ListingController::class,'update'])->name('listings.update');
    Route::delete('listings/{id}',[ListingController::class,'destroy'])->name('listings.destroy');
    Route::get('listings/{id}',[ListingController::class,'show'])->name('listings.show');
    Route::post('availability/hotels',[ListingController::class,'Availability'])->name('listings.Availability');
    Route::get('available/hotels/',[ListingController::class,'makeavailable'])->name('listings.makeAvailability');
    Route::post('photos/delete',[ListingPictureController::class,'destroy'])->name('photos.delete');
    Route::get('/hotel1/ajax',[ListingController::class,'ajax'])->name('hotels.ajax');
    Route::resource('countries',CountryController::class);
    Route::resource('cities',CityController::class);
    Route::resource('location',LocationController::class);
    Route::resource('categories',CategoryController::class);
    Route::get('/category/ajax',[CategoryController::class,'ajax'])->name('category.ajax');
});

Route::get('list/{slug}',[ListingController::class,'detail'])->name('detail');
Route::get('hotelz/{slug}',[LocationController::class,'list'])->name('viewall');
//Route::get('hotelz',[LocationController::class,'viewlist'])->name('viewlist');
Route::get('ajaxSearch',[LocationController::class,'search'])->name('ajaxSearch');
Route::get('search',[LocationController::class,'list'])->name('search');
Route::get('/profile',[UserController::class,'profile'])->name('profile');
Route::post('/profile/update',[UserController::class,'profileUpdate'])->name('profileUpdate');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    use HasFactory;
    public function cities(){
        return $this->hasMany(City::class);
    }
}

app/Http/Controllers/CountryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Country;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        if ($user->is_admin == 0) {
            $countries = Country::where('id', '>', 0)->paginate(10);
            return view('countries.index', compact('countries'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        if ($user->is_admin == 0) {
            return view('countries.create', compact('user'));
        } else {
            return redirect()->back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = Auth::user();
        if ($user->is_admin == 0) {
            $country= new Country();
            $country->name=$request->name;
            $country->save();
            $notification = array(
                'message' => 'Country Created Successfully!',
                'icon' => 'success'
            );
            return redirect()->back()->with($notification);
        }else{
            $notification = array(
                'message' => 'Country can not be created!',
                'icon' => 'warning'
            );
            return redirect()->back()->with($notification);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Country $country
     * @return \Illuminate\Http\Response
     */
    public function show(Country $country)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Country $country
     * @return \Illuminate\Http\Response
     */
    public function edit(Country $country)
    {
        $user = Auth::user();
        if ($user->is_admin == 0) {
            return view('countries.edit', compact('user'));
        }else{
            return redirect()->back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Country $country
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Country $country)
    {
        $user = Auth::user();
        if ($user->is_admin == 0) {
            $country->name=$request->name;
            $country->save();
            return redirect()->back();
        }else{
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Country $country
     * @return \Illuminate\Http\Response
     */
    public function destroy(Country $country)
    {
        $user = Auth::user();
        if ($user->is_admin == 0) {
            $country->delete();
        }
        return redirect()->back();
    }
}

resources/views/countries/create.blade.php
@extends('backoffice.master')
@section('content')
    <!--== breadcrumbs ==-->
    <div class="sb2-2-2">
        <ul>
            <li><a href="{{route('index')}}"><i class="fa fa-home" aria-hidden="true"></i> Home</a> </li>
            <li class="active-bre"><a href="#"> Add Listing Category</a> </li>
            <li class="page-back"><a href="#"><i class="fa fa-backward" aria-hidden="true"></i> Back</a> </li>
        </ul>
    </div>
    <div class="tz-2 tz-2-admin">
        <div class="tz-2-com tz-2-main">
            <h4>Add New Country</h4> <a class="dropdown-button drop-down-meta drop-down-meta-inn" href="#" data-activates="dr-list"><i class="material-icons">more_vert</i></a>
{{--            <ul id="dr-list" class="dropdown-content">--}}
{{--                <li><a href="#!">Add New</a> </li>--}}
{{--                <li><a href="#!">Edit</a> </li>--}}
{{--                <li><a href="#!">Update</a> </li>--}}
{{--                <li class="divider"></li>--}}
{{--                <li><a href="#!"><i class="material-icons">delete</i>Delete</a> </li>--}}
{{--                <li><a href="#!"><i class="material-icons">subject</i>View All</a> </li>--}}
{{--                <li><a href="#!"><i class="material-icons">play_for_work</i>Download</a> </li>--}}
{{--            </ul>--}}
            <!-- Dropdown Structure -->
            <div class="split-row">
                <div class="col-md-12">
                    <div class="box-inn-sp ad-mar-to-min">
                        <div class="tab-inn ad-tab-inn">
                            <div class="tz2-form-pay tz2-form-com">
                                <form action="{{route('countries.store')}}" method="post" enctype="multipart/form-data" >
                                    @csrf
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input type="text" name="name" class="validate"/>
                                            <label>Country Name</label>
                                        </div>
                                    </div>
{{--                                    <div class="row">--}}
{{--                                        <div class="input-field col s12">--}}
{{--                                            <select name="locations[]" multiple>--}}
{{--                                                <option value="" readonly="">Select Location</option>--}}
{{--                                                @foreach($locations as $location)--}}
{{--                                                    <option value="{{$location->id}}">{{$location->name}}</option>--}}
{{--                                                @endforeach--}}
{{--                                            </select>--}}
{{--                                        </div>--}}
{{--                                    </div>--}}
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <button type="submit" class="waves-effect waves-light full-btn">Submit</button></div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_level_scripts')
    <script type="text/javascript">
        $.notify("{{Session::get('message')}}", "{{Session::get('icon')}}");
    </script>

@endsection

resources/views/countries/edit.blade.php
<?php

resources/views/countries/index.blade.php
<?php