routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LocationController;
use \App\Http\Controllers\CountryController;
use \App\Http\Controllers\CityController;
use \App\Http\Controllers\ListingController;
use \App\Http\Controllers\UserController;
use \App\Http\Controllers\ListingPictureController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Auth::routes();
Route::get('/', [LocationController::class,'Categories'])->name('index');
Route::get('/all/listing', [LocationController::class,'Listing'])->name('listing');
Route::get('/all/city/{slug}', [LocationController::class,'city'])->name('cityListing');
Route::group(['prefix' => 'hotel', 'middleware' => ['auth', 'verified']],function () {

    Route::get('/dashboard',[UserController::class,'index'])->name('Howner');
    Route::get('listings/index',[ListingController::class,'index'])->name('listings.index');
    Route::get('listings/create',[ListingController::class,'create'])->name('listings.create');
    Route::post('listings/store',[ListingController::class,'store'])->name('listings.store');
    Route::get('listings/{id}/edit',[ListingController::class,'edit'])->name('listings.edit');
    Route::patch('listings/{id}',[ListingController::class,'update'])->name('listings.update');
    Route::delete('listings/{id}',[ListingController::class,'destroy'])->name('listings.destroy');
    Route::get('listings/{id}',[ListingController::class,'show'])->name('listings.show');
    Route::post('availability/hotels',[ListingController::class,'Availability'])->name('listings.Availability');
    Route::get('available/hotels/',[ListingController::class,'makeavailable'])->name('hotels.makeAvailability');
    Route::post('photos/delete',[ListingPictureController::class,'destroy'])->name('photos.delete');
    Route::get('/hotel1/ajax',[ListingController::class,'ajax'])->name('hotels.ajax');
    //ya get wala ha oper wala ya nichy wala nechay wala

});
Route::group(['prefix' => 'property', 'middleware' => ['auth', 'verified']],function () {

    Route::get('/dashboard',[UserController::class,'index'])->name('Powner');
    Route::get('listings/index',[ListingController::class,'index'])->name('listings.index');
    Route::get('listings/create',[ListingController::class,'create'])->name('listings.create');
    Route::post('listings/store',[ListingController::class,'store'])->name('listings.store');
    Route::get('listings/{id}/edit',[ListingController::class,'edit'])->name('listings.edit');
    Route::patch('listings/{id}',[ListingController::class,'update'])->name('listings.update');
    Route::delete('listings/{id}',[ListingController::class,'destroy'])->name('listings.destroy');
    Route::get('listings/{id}',[ListingController::class,'show'])->name('listings.show');
    Route::post('availability/hotels',[ListingController::class,'Availability'])->name('listings.Availability');
    Route::get('available/hotels/',[ListingController::class,'makeavailable'])->name('listings.makeAvailability');
    Route::post('photos/delete',[ListingPictureController::class,'destroy'])->name('photos.delete');
    Route::get('/hotel1/ajax',[ListingController::class,'ajax'])->name('hotels.ajax');

});
Route::group(['prefix' => 'user', 'middleware' => ['auth', 'verified']],function () {

    Route::get('/dashboard',[UserController::class,'index'])->name('userDashboard');
    Route::get('listings/index',[ListingController::class,'index'])->name('listings.index');
    Route::get('listings/create',[ListingController::class,'create'])->name('listings.create');
    Route::post('listings/store',[ListingController::class,'store'])->name('listings.store');
    Route::get('listings/{id}/edit',[ListingController::class,'edit'])->name('listings.edit');
    Route::patch('listings/{id}',[ListingController::class,'update'])->name('listings.update');
    Route::delete('listings/{id}',[ListingController::class,'destroy'])->name('listings.destroy');
    Route::get('listings/{id}',[ListingController::class,'show'])->name('listings.show');

    Route::post('availability/hotels',[ListingController::class,'Availability'])->name('listings.Availability');
    Route::get('available/hotels/',[ListingController::class,'makeavailable'])->name('listings.makeAvailability');
    Route::post('photos/delete',[ListingPictureController::class,'destroy'])->name('photos.delete');
    Route::get('/hotel1/ajax',[ListingController::class,'ajax'])->name('hotels.ajax');
});
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'verified']],function () {

    Route::get('/dashboard',[UserController::class,'index'])->name('adminDashboard');
    Route::get('listings/index',[ListingController::class,'index'])->name('listings.index');
    Route::get('listings/create',[ListingController::class,'create'])->name('listings.create');
    Route::post('listings/store',[ListingController::class,'store'])->name('listings.store');
    Route::get('listings/{id}/edit',[ListingController::class,'edit'])->name('listings.edit');
    Route::patch('listings/{id}',[ListingController::class,'update'])->name('listings.update');
    Route::delete('listings/{id}',[ListingController::class,'destroy'])->name('listings.destroy');
    Route::get('listings/{id}',[ListingController::class,'show'])->name('listings.show');
    Route::post('availability/hotels',[ListingController::class,'Availability'])->name('listings.Availability');
    Route::get('available/hotels/',[ListingController::class,'makeavailable'])->name('listings.makeAvailability');
    Route::post('photos/delete',[ListingPictureController::class,'destroy'])->name('photos.delete');
    Route::get('/hotel1/ajax',[ListingController::class,'ajax'])->name('hotels.ajax');
    Route::resource('countries',CountryController::class);
    Route::resource('cities',CityController::class);
    Route::resource('location',LocationController::class);
    Route::resource('categories',CategoryController::class);
    Route::get('/category/ajax',[CategoryController::class,'ajax'])->name('category.ajax');
});

Route::get('list/{slug}',[ListingController::class,'detail'])->name('detail');
Route::get('hotelz/{slug}',[LocationController::class,'list'])->name('viewall');
//Route::get('hotelz',[LocationController::class,'viewlist'])->name('viewlist');
Route::get('ajaxSearch',[LocationController::class,'search'])->name('ajaxSearch');
Route::get('search',[LocationController::class,'list'])->name('search');
Route::get('/profile',[UserController::class,'profile'])->name('profile');
Route::post('/profile/update',[UserController::class,'profileUpdate'])->name('profileUpdate');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    public function locations(){
        return $this->belongsToMany(Location::class);
    }
    public function listing(){
        return $this->belongsTo(Listing::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Location;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories=Category::with('locations')->paginate(12);
        return view('categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $locations=Location::all();
        return view('categories.create',compact('locations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        return $request;
        $category=new Category();
        $category->name=$request->name;
        $category->save();
        $category->locations()->sync($request->locations,false);
        $notification = array(
            'message' => 'Category Created Successfully!',
            'icon' => 'success'
        );
        return redirect()->back()->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $locations=Location::all();
        return view('categories.edit',compact('category','locations'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $category->name=$request->name;
        $category->save();
        $category->locations()->sync($request->locations,false);
        $notification = array(
            'message' => 'Category Updated Successfully!',
            'icon' => 'success'
        );
        return redirect()->back()->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
    public function ajax()
    {
        $categories = Category::with( 'locations')->get();
//        return $categories;

        return Datatables::of($categories)
            ->addColumn('action', function (Category $category) {
                $btn = '<div class="d-flex"><a href="categories/' . $category->id . '/edit" class="btn btn-primary" title="Edit"><i class="fa fa-edit"></i></a><a href="categories/' . $category->id . '" class="btn btn-primary" title="Show"><i class="fa fa-eye"></i></a></div>';
                return $btn;
            })
            ->addColumn('location',function($categories){
                $locationz=[];
                foreach($categories->locations as $location){
                     array_push($locationz,$location->name);
                }
                return $locationz;
            })
            ->rawColumns(['location','action'])
            ->make(true);
    }
}

resources/views/categories/create.blade.php
@extends('backoffice.master')
@section('content')
    <!--== breadcrumbs ==-->
    <div class="sb2-2-2">
        <ul>
            <li><a href="{{route('index')}}"><i class="fa fa-home" aria-hidden="true"></i> Home</a> </li>
            <li class="active-bre"><a href="#"> Add Listing Category</a> </li>
            <li class="page-back"><a href="#"><i class="fa fa-backward" aria-hidden="true"></i> Back</a> </li>
        </ul>
    </div>
    <div class="tz-2 tz-2-admin">
        <div class="tz-2-com tz-2-main">
            <h4>Add Listing Category</h4> <a class="dropdown-button drop-down-meta drop-down-meta-inn" href="#" data-activates="dr-list"><i class="material-icons">more_vert</i></a>
            <ul id="dr-list" class="dropdown-content">
                <li><a href="#!">Add New</a> </li>
                <li><a href="#!">Edit</a> </li>
                <li><a href="#!">Update</a> </li>
                <li class="divider"></li>
                <li><a href="#!"><i class="material-icons">delete</i>Delete</a> </li>
                <li><a href="#!"><i class="material-icons">subject</i>View All</a> </li>
                <li><a href="#!"><i class="material-icons">play_for_work</i>Download</a> </li>
            </ul>
            <!-- Dropdown Structure -->
            <div class="split-row">
                <div class="col-md-12">
                    <div class="box-inn-sp ad-mar-to-min">
                        <div class="tab-inn ad-tab-inn">
                            <div class="tz2-form-pay tz2-form-com">
                                <form action="{{route('categories.store')}}" method="post" enctype="multipart/form-data" >
                                @csrf
                                <div class="row">
                                        <div class="input-field col s12">
                                            <input type="text" name="name" class="validate"/>
                                            <label>Category Name</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <select name="locations[]" multiple>
                                                <option value="" readonly="">Select Location</option>
                                                @foreach($locations as $location)
                                                    <option value="{{$location->id}}">{{$location->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <button type="submit" class="waves-effect waves-light full-btn">Submit</button></div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_level_scripts')
    <script type="text/javascript">
        import Button from "../../js/Jetstream/Button";
        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 6000
        });
        export default {
            components: {Button}
        }
    </script>

    <script type="text/javascript">
        // $('.toastrDefaultSuccess').click(function() {
        toastr.{{Session::get('icon')}}("{{Session::get('message')}}");
        // });
    </script>

@endsection

resources/views/categories/edit.blade.php
@extends('backoffice.master')
@section('content')
    <!--== breadcrumbs ==-->
    <div class="sb2-2-2">
        <ul>
            <li><a href="{{route('index')}}"><i class="fa fa-home" aria-hidden="true"></i> Home</a> </li>
            <li class="active-bre"><a href="#"> Add Listing Category</a> </li>
            <li class="page-back"><a href="#"><i class="fa fa-backward" aria-hidden="true"></i> Back</a> </li>
        </ul>
    </div>
    <div class="tz-2 tz-2-admin">
        <div class="tz-2-com tz-2-main">
            <h4>Edit Listing Category</h4> <a class="dropdown-button drop-down-meta drop-down-meta-inn" href="#" data-activates="dr-list"><i class="material-icons">more_vert</i></a>
            <ul id="dr-list" class="dropdown-content">
                <li><a href="#!">Add New</a> </li>
                <li><a href="#!">Edit</a> </li>
                <li><a href="#!">Update</a> </li>
                <li class="divider"></li>
                <li><a href="#!"><i class="material-icons">delete</i>Delete</a> </li>
                <li><a href="#!"><i class="material-icons">subject</i>View All</a> </li>
                <li><a href="#!"><i class="material-icons">play_for_work</i>Download</a> </li>
            </ul>
            <!-- Dropdown Structure -->
            <div class="split-row">
                <div class="col-md-12">
                    <div class="box-inn-sp ad-mar-to-min">
                        <div class="tab-inn ad-tab-inn">
                            <div class="tz2-form-pay tz2-form-com">
                                <form action="{{route('categories.update',$category->id)}}" method="post" enctype="multipart/form-data" >
                                    @csrf
                                    @method('PUT')
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input type="text" name="name" class="validate" value="{{$category->name}}"/>
                                            <label>Category Name</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <select name="locations[]" multiple>
                                                <option value="" readonly="">Select Location</option>
                                                @foreach($locations as $location)
                                                    <option value="{{$location->id}}">{{$location->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <button type="submit" class="waves-effect waves-light full-btn">Submit</button></div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('page_level_scripts')
    <script type="text/javascript">
        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 6000
        });
    </script>

    <script type="text/javascript">
        // $('.toastrDefaultSuccess').click(function() {
        toastr.{{Session::get('icon')}}("{{Session::get('message')}}");
        // });
    </script>

@endsection

resources/views/categories/index.blade.php
@extends('backoffice.master')
@section('content')
    <!--== breadcrumbs ==-->
    <div class="sb2-2-2">
        <ul>
            <li><a href="#"><i class="fa fa-home" aria-hidden="true"></i> Home</a> </li>
            <li class="active-bre"><a href="#">All Categories</a> </li>
            <li class="page-back"><a href="#"><i class="fa fa-backward" aria-hidden="true"></i>Back</a> </li>
        </ul>
    </div>
    <div class="tz-2 tz-2-admin">
        <div class="tz-2-com tz-2-main">
            <div class="split-row">
                <div class="col-md-12">
                    <div class="box-inn-sp ad-inn-page">
                        <div class="tab-inn ad-tab-inn">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>NAME</th>
                                        <th>LOCATION</th>
                                        <th>ACTION</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($categories as $category)
                                        <tr>
                                            <td><a href="#"><span class="list-enq-name">{{$category->id}}</span></a> </td>
                                            <td><a href="#"><span class="list-enq-name">{{$category->name}}</span></a> </td>
                                            <td><span class="list-enq-city">@foreach($category->locations as $location){{$location->name}},@endforeach</td>
                                            <td> <a href="{{route('categories.edit',$category->id)}}"><i class="fa fa-edit"></i></a> </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="admin-pag-na">
                        {{ $categories->links() }}
                    </div>
                </div>
            </div>

            <!-- /.card-body -->
        </div>
    </div>

@endsection
@section('page_level_scripts')
    <script>
        $(document).ready(function (){
            $('#category').DataTable({
                processing: true,
                serverSide: true,
                responsive:true,
                ajax: '{{ route('category.ajax') }}',
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'name', name: 'name' },
                    { data: 'location', name: 'location' },
                    { data: 'action', name: 'action' }
                ]
            })
        })
    </script>
@endsection